[tool.poetry]
name = "dashboard-project"
version = "0.1.0"
description = ""
authors = ["Pedro Salomão <pedro-svm@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
jinja2 = "^3.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
